#!/bin/sh 

# Internal laptop display
if xrandr | rg -q 'connected.*3840x2160'
then
  DPI=192

  echo 'user_pref("general.smoothScroll", false);' > $HOME/.mozilla/firefox/3xwysgr6.default-release/user.js
  sd 'hide_edge_borders.*' 'hide_edge_borders smart' $HOME/.config/i3/config

# External display(s)
else
  DPI=96

  echo 'user_pref("general.smoothScroll", true);' > $HOME/.mozilla/firefox/3xwysgr6.default-release/user.js
  sd 'hide_edge_borders.*' 'hide_edge_borders none' $HOME/.config/i3/config
fi

# Update ~/.Xresources
sd "Xcursor.size.*" "Xcursor.size:  $((DPI/6))" $HOME/.Xresources 
sd "Xft.dpi.*" "Xft.dpi:       $DPI"     $HOME/.Xresources 

# Update ~/.config/spotify-launcher.conf
echo "[spotify]
extra_arguments = [\"--force-device-scale-factor=$((DPI/96))\"]
" > $HOME/.config/spotify-launcher.conf

# Update ~/.xsettingsd
echo "Xcursor/size            $((DPI/6))
Gtk/CursorThemeSize     $((DPI/6)) 
Xft/DPI                 $((DPI*1024))
Gdk/WindowScalingFactor $((DPI/96))
Gdk/UnscaledDPI         $((DPI*1024/(DPI/96)))
" > $HOME/.xsettingsd

# Reload config files
killall -HUP xsettingsd
xrdb $HOME/.Xresources
i3-msg restart

