return {
  "stevearc/conform.nvim",
  opts = {
    formatters_by_ft = {
      ["javascript"] = { "biome-check" },
      ["javascriptreact"] = { "biome-check" },
      ["typescript"] = { "biome-check" },
      ["typescriptreact"] = { "biome-check" },
      ["vue"] = { "prettierd" },
      ["css"] = { "prettierd" },
      ["scss"] = { "prettierd" },
      ["less"] = { "prettierd" },
      ["html"] = { "prettierd" },
      ["json"] = { "biome-check" },
      ["jsonc"] = { "biome-check" },
      ["yaml"] = { "prettierd" },
      ["markdown"] = { "prettierd" },
      ["markdown.mdx"] = { "prettierd" },
      ["graphql"] = { "prettierd" },
      ["handlebars"] = { "prettierd" },
      ["typst"] = { "typstfmt" },
      ["tex"] = { "latexindent" },
      ["sql"] = { "sql-formatter" },
    },
  },
}
